services:
  - type: web
    name: virtual-ta-tds
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn vta_api2:app --host=0.0.0.0 --port=8000
    pythonVersion: 3.10.13
